version: "0.1"  # optional since v1.27.0
services:
  rtorrent:
    image: wonderfall/rtorrent-flood
    container_name: rtorrent
    restart: unless-stopped
    tty: true
    security_opt:
      - no-new-privileges:true
    ports:
      - 49184:49184
      - 49184:49184/udp
    environment:
      - UID=1000
      - GID=1000
      - FLOOD_SECRET=UqfHzXuPUDCwOZ2POnWL9Rkp1hh9y5
      - RTORRENT_SOCK=true
    volumes:
      - type: volume
        source: rtor-watchdir
        target: /watchdir
      - type: volume
        source: rtor-data
        target: /dropbox/torrent
      - /home/docker/flood:/flood-db
    networks:
      - http_network
      - rtorrent_network
    labels:
      - traefik.enable=true
      - traefik.http.routers.rtorrent.entrypoints=http
      - traefik.http.routers.rtorrent.rule=Host(`box.domain.tld`)
      - traefik.http.routers.rtorrent.middlewares=https-redirect@file
      - traefik.http.routers.rtorrent-secure.entrypoints=https
      - traefik.http.routers.rtorrent-secure.rule=Host(`box.domain.tld`)
      - traefik.http.routers.rtorrent-secure.tls=true
      - traefik.http.routers.rtorrent-secure.middlewares=secure-headers@file,hsts-headers@file
      - traefik.http.routers.rtorrent-secure.tls.certresolver=http
      - traefik.http.routers.rtorrent-secure.service=rtorrent
      - traefik.http.services.rtorrent.loadbalancer.server.port=3000
      - traefik.docker.network=http_network
volumes:
  rtor-watchdir:
    driver_opts:
      type: nfs
      o: "addr=192.168.0.145,bg,hard,rw"
      device: ":/share/DropBox"
  rtor-data:
    driver_opts:
      type: nfs
      o: "addr=192.168.0.145,bg,hard,rw"
      device: ":/share/watch"